### ISSUE TITLE
getContent error

### ISSUE THREAD

**Issue by amjadniazi48** [lovata/oc-buddies-plugin#11]
i m getting this error after placing registration/login component on cms page

> Call to a member function getContent() on null" on line 328 of /home3/bikesale/public_html/modules/cms/controllers/Index.php

and following erro message when in browse the login/register page 

> Class name is not registered for the component "session". Check the component plugin.
> /home3/bikesale/public_html/modules/cms/classes/ComponentManager.php line 200

**Comment by kharanenka** [comment]
Hi! Please send the page code with components
