### ISSUE TITLE
UserPage

### ISSUE THREAD

**Issue by chrisvidal** [lovata/oc-buddies-plugin#21]
Hi

I followed the documentation for the UserPage component and have some questions:
- how the user data are retrieved in the component?
- in the example I see I that need to use {{ arForm.email }} for example, but this is empty when I display the userpage after login.

Thanks

**Comment by kharanenka** [comment]
Hi! 
You can get User object from UserData component
```
{% set obUser = UserData.get %}
{{ obUser.email }}
```
The example shows how to make form without javascript, using simple submit form.
```
{% set arForm = UserPage.getOldFormData %}
```
This code is used to get old input values filled by the user.
If you submit form with ajax, you may not use this code at all.
```
{# Simple submit form without ajax #}
<input type="email" value="{{ arForm.email|default(obUser.email) }}">
{# Submit form with ajax #}
<input type="email" value="{{ obUser.email }}">
```

**Comment by chrisvidal** [comment]
ok I get it, so for the user account page, I would need to have UserPage and UserData component in the page. 
Thanks
