### ISSUE TITLE
add form registration

### ISSUE THREAD

**Issue by mattiak14** [lovata/oc-buddies-plugin#7]
Hello
I'm trying to use the plugin for friends
I'm trying to include the registration form on a frontend page ... but I do not understand 2 things:
- the form is not added in the page with the syntax {% component 'Registration' %} ?
- if I create the form manually(html) which action should the form be associated with?

thanks

**Comment by kharanenka** [comment]
Hi! Our components do not have their own templates. You can find simple example in documentation. Simple views will not be used in real projects. You will need to write your own views. If you need a simple example, then it is  in documentation.
For example (ajax request):
```
$('form').request('Registration::onAjax');
```

**Comment by mattiak14** [comment]
thank you
sorry but I still do not have much experience on octobercms ... be patient
on my project I added the acme-laravelapi plugin to create my frontend
in my controller how can I call the buddies plugin functions? how to login, register?
thank you

**Comment by kharanenka** [comment]
You can use register(), login(), logout(), getUser() methods of Lovata\Buddies\Facades\AuthHelper class
