### ISSUE TITLE
Email activation-link loaded via env-var instead config

### ISSUE THREAD

**Issue by gbaumeister** [lovata/oc-buddies-plugin#9]
The `Lovata\Buddies\Components\Registration` class uses `env('SITE_URL')` to load the sites URL.  
Environment variables are often not set (especially if DotEnv syntax is not used), which results in an unusable Activation Link.

Instead I would suggest to load the url via the configuration: `config('app.url')`.

**Comment by kharanenka** [comment]
Fixed in version 1.2.0
